services:
  - type: web
    name: test-backend
    env: python
    python:
      version: 3.9.0
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
